sudo: false
language: python
matrix:
  fast_finish: true
  include:
    # Python version is just for the look on travis.
    - python: 2.7
      env: TOXENV=flake8-py27

    - python: 3.5
      env: TOXENV=flake8-py35

    - python: 2.7
      env: TOXENV=py27-django111

    - python: 3.5
      env: TOXENV=py35-django111

    - python: 3.5
      env: TOXENV=py35-django20

    - python: 3.5
      env: TOXENV=py35-djangomaster

    - python: 3.6
      env: TOXENV=py36-django111

    - python: 3.6
      env: TOXENV=py36-django20
  
    - python: 3.6
      env: TOXENV=py36-djangomaster

  allow_failures:
    - env: TOXENV=py35-djangomaster
    - env: TOXENV=py36-djangomaster

install:
    - pip install tox

script:
    - tox -e $TOXENV