# In order to use the container infrastructure
sudo: false
language: python
# Using Python 3.5 to make sure it's installed.
python:
  - 3.5
env:
  - TOX_ENV=py27-django18
  - TOX_ENV=py27-django19
  - TOX_ENV=py27-django110
  - TOX_ENV=py34-django18
  - TOX_ENV=py34-django19
  - TOX_ENV=py34-django110
  - TOX_ENV=py35-django18
  - TOX_ENV=py35-django19
  - TOX_ENV=py35-django110
  - TOX_ENV=flake8
script: tox -e $TOX_ENV
install:
    - pip install tox
